# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HITs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerItemHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('expireDuration', models.BigIntegerField()),
                ('instructions', models.TextField()),
                ('estimateTime', models.BigIntegerField()),
                ('workersCount', models.IntegerField()),
                ('reward', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answeritemhit',
            name='hit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HITs.Hit'),
        ),
    ]
